# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import article_pb2 as article__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in article_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArticleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateArticle = channel.unary_unary(
                '/article.ArticleService/CreateArticle',
                request_serializer=article__pb2.CreateArticleRequest.SerializeToString,
                response_deserializer=article__pb2.CreateArticleResponse.FromString,
                _registered_method=True)
        self.ReadArticle = channel.unary_unary(
                '/article.ArticleService/ReadArticle',
                request_serializer=article__pb2.ReadArticleRequest.SerializeToString,
                response_deserializer=article__pb2.ReadArticleResponse.FromString,
                _registered_method=True)
        self.UpdateArticle = channel.unary_unary(
                '/article.ArticleService/UpdateArticle',
                request_serializer=article__pb2.UpdateArticleRequest.SerializeToString,
                response_deserializer=article__pb2.UpdateArticleResponse.FromString,
                _registered_method=True)
        self.DeleteArticle = channel.unary_unary(
                '/article.ArticleService/DeleteArticle',
                request_serializer=article__pb2.DeleteArticleRequest.SerializeToString,
                response_deserializer=article__pb2.DeleteArticleResponse.FromString,
                _registered_method=True)
        self.ListArticle = channel.unary_unary(
                '/article.ArticleService/ListArticle',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=article__pb2.ListArticleResponse.FromString,
                _registered_method=True)


class ArticleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArticleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArticle,
                    request_deserializer=article__pb2.CreateArticleRequest.FromString,
                    response_serializer=article__pb2.CreateArticleResponse.SerializeToString,
            ),
            'ReadArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArticle,
                    request_deserializer=article__pb2.ReadArticleRequest.FromString,
                    response_serializer=article__pb2.ReadArticleResponse.SerializeToString,
            ),
            'UpdateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateArticle,
                    request_deserializer=article__pb2.UpdateArticleRequest.FromString,
                    response_serializer=article__pb2.UpdateArticleResponse.SerializeToString,
            ),
            'DeleteArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArticle,
                    request_deserializer=article__pb2.DeleteArticleRequest.FromString,
                    response_serializer=article__pb2.DeleteArticleResponse.SerializeToString,
            ),
            'ListArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArticle,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=article__pb2.ListArticleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'article.ArticleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('article.ArticleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArticleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/article.ArticleService/CreateArticle',
            article__pb2.CreateArticleRequest.SerializeToString,
            article__pb2.CreateArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/article.ArticleService/ReadArticle',
            article__pb2.ReadArticleRequest.SerializeToString,
            article__pb2.ReadArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/article.ArticleService/UpdateArticle',
            article__pb2.UpdateArticleRequest.SerializeToString,
            article__pb2.UpdateArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/article.ArticleService/DeleteArticle',
            article__pb2.DeleteArticleRequest.SerializeToString,
            article__pb2.DeleteArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/article.ArticleService/ListArticle',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            article__pb2.ListArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
